-- insert user roles to database
-- insert into authority (name) values ('ROLE_ADMIN')
-- insert into role (name) values ('ROLE_MANAGER')
-- insert into role (name) values ('ROLE_TEACHER')
-- insert into role (name) values ('ROLE_USER')
